version: '3.8'

services:
  client_server:
    build:
      context: ./app
    image: caffeinated-odyssey-client
    container_name: client_server
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: ["uvicorn", "client_server:app", "--host", "0.0.0.0", "--port", "8000"]

  worker_server:
    build:
      context: ./app
    image: caffeinated-odyssey-worker
    container_name: worker_server
    depends_on:
      - client_server
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    command: ["uvicorn", "worker_server:app", "--host", "0.0.0.0", "--port", "8001"]
